const preguntasPcb = [
	{
		id: "1",
		enunciado: "Para corroer (atacar) una placa virgen de circuito impreso se usa:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "cloruro ferroso o percloruro ferroso" },
			{ val: "b", txt: "sulfato ferroso" },
			{ val: "c", txt: "otra solución ácida", esOk:true },
			{ val: "d", txt: "bromuro férrico o perbromuro férrico" },
			{ val: "e", txt: "cloruro sódico o percloruro sódico" },
		],
	},
	{
		id: "2",
		enunciado: "Según sugerencia de la cátedra durante el armado del PCB:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "se corta y luego se suelda.", esOk: true },
			{ val: "b", txt: "se suelda y luego se corta." },
		],
	},
	{
		id: "3",
		enunciado: "El flux se usa para:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "evitar la soldadura posterior" },
			{ val: "b", txt: "lograr una terminación brillosa" },
			{ val: "c", txt: "proteger del sol" },
			{ val: "d", txt: "adherir los componentes" },
			{ val: "e", txt: "evitar la oxidación del circuito impreso", esOk: true },
		],
	},
	{
		id: "4",
		enunciado: "En la realización del circuito impreso de este curso, se marcó con un punzón:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "las iniciales del alumno" },
			{ val: "b", txt: "la ubicación de los agujeros", esOk: true },
			{ val: "c", txt: "la zona exterior de la plaqueta" },
			{ val: "d", txt: "la mesa de trabajo" },
			{ val: "e", txt: "el contorno de las pistas" },
		],
	},
	{
		id: "5",
		enunciado: "¿Qué se utiliza para realizar un circuito impreso?",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "placa virgen cobreada", esOk: true },
			{ val: "b", txt: "placa virgen estañada" },
			{ val: "c", txt: "placa virgen perforada" },
			{ val: "d", txt: "placa virgen dorada" },
			{ val: "e", txt: "placa virgen bronceada" },
		],
	},
	{
		id: "6",
		enunciado: "La potencia del soldador recomandado para electrónica es de:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "100 W tipo lápiz" },
			{ val: "b", txt: "menor a 15 W" },
			{ val: "c", txt: "60 W" },
			{ val: "d", txt: "30/40 W", esOk: true },
		],
	},
	{
		id: "7",
		enunciado: "En la confección de un circuito impreso, el jabón común se utiliza para:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "limpiar el flux" },
			{ val: "b", txt: "contrarrestar la acción del oxígeno" },
			{ val: "c", txt: "anular la acción corrosiva del ácido", esOk: true },
			{ val: "d", txt: "limpiar la tinta" },
			{ val: "e", txt: "facilitar la soldadura" },
		],
	},
	{
		id: "8",
		enunciado: "La solución que se utilizó para corroer la placa virgen de circuito impreso se:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "descartó como residuo" },
			{ val: "b", txt: "se evaporó para obtener un viaje gratis" },
			{ val: "c", txt: "vertió en el desagüe cloacal" },
			{ val: "d", txt: "vertió en el desagüe pluvial" },
			{ val: "e", txt: "guardó en un recipiente para un próximo uso", esOk: true },
		],
	},
	{
		id: "9",
		enunciado: "Para corroer una placa virgen de circuito impreso, de preferencia se calienta la solución ácida precia o simultáneamente a través de un baño calefactor entre:",
		tipo: "radio",
		shuffle: true,
		opciones: [
			{ val: "a", txt: "nunca se calienta" },
			{ val: "b", txt: "45 °C y 55 °C" },
			{ val: "c", txt: "15 °C y 20 °C" },
			{ val: "d", txt: "hasta 75 °C" },
			{ val: "e", txt: "25 °C y 35 °C", esOk: true },
		],
	},
	{
		id: "10",
		enunciado: "Para evitar sobrecalentar los componentes, ¿es conveniente \"soplar\" la soldadura una vez realizada?",
		tipo: "radio",
		opciones: [
			{ val: "a", txt: "Verdadero" },
			{ val: "b", txt: "Falso", esOk: true },
		],
	},
];
